# nginx/nginx.conf

# กำหนดกลุ่มของเซิร์ฟเวอร์ backend ของเรา
upstream backend_servers {
    # 'backend' คือชื่อ service ใน docker-compose.yml
    # '8000' คือ PORT ที่ backend app ของคุณรันอยู่ภายใน container
    server backend:8000;
}

server {
    # Nginx จะรอฟัง request ที่ port 80 (http)
    listen 80;

    # สำหรับทุก request ที่เข้ามา
    location / {
        # ส่งต่อ (proxy) request ทั้งหมดไปยังกลุ่มเซิร์ฟเวอร์ที่เราตั้งไว้
        proxy_pass http://backend_servers;

        # ตั้งค่า header เพิ่มเติมเพื่อให้ข้อมูลของ client เดิมถูกส่งไปยัง backend app ด้วย
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}